// <auto-generated />
using System;
using MiApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Backend_RSV.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251113185232_CambioDeFechaVencimientoUsuario")]
    partial class CambioDeFechaVencimientoUsuario
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AlertaPanico", b =>
                {
                    b.Property<int>("AlertaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AlertaID"));

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Latitud")
                        .HasColumnType("decimal(10,8)");

                    b.Property<decimal>("Longitud")
                        .HasColumnType("decimal(11,8)");

                    b.Property<int>("UsuarioID")
                        .HasColumnType("int");

                    b.HasKey("AlertaID");

                    b.HasIndex("UsuarioID");

                    b.ToTable("AlertasPanico");
                });

            modelBuilder.Entity("Amenidad", b =>
                {
                    b.Property<int>("AmenidadID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AmenidadID"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<int?>("Capacidad")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("TipoAmenidadID")
                        .HasColumnType("int");

                    b.Property<string>("Ubicacion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("AmenidadID");

                    b.HasIndex("TipoAmenidadID");

                    b.ToTable("Amenidades");
                });

            modelBuilder.Entity("Aviso", b =>
                {
                    b.Property<int>("AvisoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AvisoID"));

                    b.Property<int>("CategoriaID")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("FechaEvento")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaPublicacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("UsuarioID")
                        .HasColumnType("int");

                    b.HasKey("AvisoID");

                    b.HasIndex("CategoriaID");

                    b.HasIndex("UsuarioID");

                    b.ToTable("Avisos");
                });

            modelBuilder.Entity("CargoMantenimiento", b =>
                {
                    b.Property<int>("CargoMantenimientoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CargoMantenimientoID"));

                    b.Property<string>("Concepto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("FechaVencimiento")
                        .HasColumnType("date");

                    b.Property<decimal>("Monto")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("MontoPagado")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int?>("PersonalMantenimientoID")
                        .HasColumnType("int");

                    b.Property<decimal>("SaldoPendiente")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasComputedColumnSql("[Monto] - [MontoPagado]", true);

                    b.Property<int?>("UsuarioID")
                        .HasColumnType("int");

                    b.HasKey("CargoMantenimientoID");

                    b.HasIndex("PersonalMantenimientoID");

                    b.HasIndex("UsuarioID");

                    b.ToTable("CargosMantenimiento");
                });

            modelBuilder.Entity("CargoServicio", b =>
                {
                    b.Property<int>("CargoServicioID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CargoServicioID"));

                    b.Property<string>("Concepto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Monto")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("MontoPagado")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("SaldoPendiente")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasComputedColumnSql("[Monto] - [MontoPagado]", true);

                    b.Property<int>("SolicitudID")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioID")
                        .HasColumnType("int");

                    b.HasKey("CargoServicioID");

                    b.HasIndex("SolicitudID");

                    b.HasIndex("UsuarioID");

                    b.ToTable("CargosServicios");
                });

            modelBuilder.Entity("CategoriaAviso", b =>
                {
                    b.Property<int>("CategoriaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoriaID"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("CategoriaID");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("CategoriasAviso");
                });

            modelBuilder.Entity("ComprobantePago", b =>
                {
                    b.Property<int>("ComprobanteID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ComprobanteID"));

                    b.Property<byte[]>("Archivo")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<DateTime>("FechaSubida")
                        .HasColumnType("datetime2");

                    b.Property<string>("NombreArchivo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("PagoID")
                        .HasColumnType("int");

                    b.Property<string>("TipoArchivo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ComprobanteID");

                    b.HasIndex("PagoID")
                        .IsUnique();

                    b.ToTable("ComprobantesPago");
                });

            modelBuilder.Entity("CuentaUsuario", b =>
                {
                    b.Property<int>("CuentaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CuentaID"));

                    b.Property<string>("FechaVencimiento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("NumeroTarjeta")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<decimal>("SaldoMantenimiento")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("SaldoServicios")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("SaldoTotal")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("UltimaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("UltimosDigitos")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<int>("UsuarioID")
                        .HasColumnType("int");

                    b.HasKey("CuentaID");

                    b.HasIndex("UsuarioID")
                        .IsUnique();

                    b.ToTable("CuentaUsuario");
                });

            modelBuilder.Entity("DetallePago", b =>
                {
                    b.Property<int>("DetalleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DetalleID"));

                    b.Property<int>("CargoID")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaAplicacion")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("MontoAplicado")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("PagoID")
                        .HasColumnType("int");

                    b.Property<string>("TipoCargo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("DetalleID");

                    b.HasIndex("PagoID");

                    b.ToTable("DetallePago");
                });

            modelBuilder.Entity("Invitado", b =>
                {
                    b.Property<int>("InvitadoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InvitadoID"));

                    b.Property<string>("ApellidoMaternoInvitado")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ApellidoPaternoInvitado")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CodigoQR")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("FechaEntrada")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaGeneracion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaSalida")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaVencimiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("NombreInvitado")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("UsuarioID")
                        .HasColumnType("int");

                    b.HasKey("InvitadoID");

                    b.HasIndex("CodigoQR")
                        .IsUnique();

                    b.HasIndex("UsuarioID");

                    b.ToTable("Invitados");
                });

            modelBuilder.Entity("MarcadorMapa", b =>
                {
                    b.Property<int>("MarcadorID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MarcadorID"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Comentario")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Indicador")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<decimal>("Latitud")
                        .HasColumnType("decimal(10,8)");

                    b.Property<decimal>("Longitud")
                        .HasColumnType("decimal(11,8)");

                    b.Property<int?>("UsuarioID")
                        .HasColumnType("int");

                    b.HasKey("MarcadorID");

                    b.HasIndex("UsuarioID");

                    b.ToTable("MarcadoresMapa");
                });

            modelBuilder.Entity("Pago", b =>
                {
                    b.Property<int>("PagoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PagoID"));

                    b.Property<int?>("CargoMantenimientoID")
                        .HasColumnType("int");

                    b.Property<int?>("CargoServicioID")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaPago")
                        .HasColumnType("datetime2");

                    b.Property<string>("FolioUnico")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MetodoPago")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<decimal>("MontoTotal")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("TipoPago")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("UltimosDigitosTarjeta")
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<int>("UsuarioID")
                        .HasColumnType("int");

                    b.HasKey("PagoID");

                    b.HasIndex("CargoMantenimientoID");

                    b.HasIndex("CargoServicioID");

                    b.HasIndex("FolioUnico")
                        .IsUnique();

                    b.HasIndex("UsuarioID");

                    b.ToTable("Pagos");
                });

            modelBuilder.Entity("Persona", b =>
                {
                    b.Property<int>("PersonaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PersonaID"));

                    b.Property<string>("ApellidoMaterno")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ApellidoPaterno")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateOnly?>("FechaNacimiento")
                        .HasColumnType("date");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("PersonaID");

                    b.ToTable("Personas");
                });

            modelBuilder.Entity("PersonalMantenimiento", b =>
                {
                    b.Property<int>("PersonalMantenimientoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PersonalMantenimientoID"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("DiasLaborales")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateOnly>("FechaContratacion")
                        .HasColumnType("date");

                    b.Property<string>("Notas")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("PersonaID")
                        .HasColumnType("int");

                    b.Property<string>("Puesto")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Sueldo")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("TipoContrato")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Turno")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("PersonalMantenimientoID");

                    b.HasIndex("PersonaID")
                        .IsUnique();

                    b.ToTable("PersonalMantenimiento");
                });

            modelBuilder.Entity("QRPersonal", b =>
                {
                    b.Property<int>("QRID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QRID"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("CodigoQR")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("FechaGeneracion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaVencimiento")
                        .HasColumnType("datetime2");

                    b.Property<int>("UsuarioID")
                        .HasColumnType("int");

                    b.HasKey("QRID");

                    b.HasIndex("CodigoQR")
                        .IsUnique();

                    b.HasIndex("UsuarioID");

                    b.ToTable("QRPersonales");
                });

            modelBuilder.Entity("Reporte", b =>
                {
                    b.Property<int>("ReporteID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReporteID"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("DireccionTexto")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("EsAnonimo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Imagen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Latitud")
                        .HasColumnType("decimal(10,8)");

                    b.Property<decimal>("Longitud")
                        .HasColumnType("decimal(11,8)");

                    b.Property<int>("TipoReporteID")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("UsuarioID")
                        .HasColumnType("int");

                    b.Property<bool>("Visto")
                        .HasColumnType("bit");

                    b.HasKey("ReporteID");

                    b.HasIndex("TipoReporteID");

                    b.HasIndex("UsuarioID");

                    b.ToTable("Reportes");
                });

            modelBuilder.Entity("Reserva", b =>
                {
                    b.Property<int>("ReservaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReservaID"));

                    b.Property<int>("AmenidadID")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("FechaReserva")
                        .HasColumnType("date");

                    b.Property<TimeSpan>("HoraFin")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("HoraInicio")
                        .HasColumnType("time");

                    b.Property<string>("Motivo")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("UsuarioID")
                        .HasColumnType("int");

                    b.HasKey("ReservaID");

                    b.HasIndex("AmenidadID");

                    b.HasIndex("UsuarioID");

                    b.ToTable("Reservas");
                });

            modelBuilder.Entity("ServiciosCatalogo", b =>
                {
                    b.Property<int>("ServicioID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ServicioID"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<bool>("Disponible")
                        .HasColumnType("bit");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("NombreEncargado")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NotasInternas")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("NumeroServiciosCompletados")
                        .HasColumnType("int");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("TipoServicioID")
                        .HasColumnType("int");

                    b.HasKey("ServicioID");

                    b.HasIndex("TipoServicioID");

                    b.ToTable("ServiciosCatalogo");
                });

            modelBuilder.Entity("SolicitudesServicio", b =>
                {
                    b.Property<int>("SolicitudID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SolicitudID"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<DateTime?>("FechaAsignacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaCompletado")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly?>("FechaPreferida")
                        .HasColumnType("date");

                    b.Property<TimeSpan?>("HoraPreferida")
                        .HasColumnType("time");

                    b.Property<string>("NotasAdmin")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("PersonaAsignado")
                        .HasColumnType("int");

                    b.Property<int>("TipoServicioID")
                        .HasColumnType("int");

                    b.Property<string>("Urgencia")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("UsuarioID")
                        .HasColumnType("int");

                    b.HasKey("SolicitudID");

                    b.HasIndex("PersonaAsignado");

                    b.HasIndex("TipoServicioID");

                    b.HasIndex("UsuarioID");

                    b.ToTable("SolicitudesServicio");
                });

            modelBuilder.Entity("TipoAmenidad", b =>
                {
                    b.Property<int>("TipoAmenidadID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TipoAmenidadID"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<TimeSpan>("HorarioFin")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("HorarioInicio")
                        .HasColumnType("time");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("TipoAmenidadID");

                    b.ToTable("TiposAmenidad");
                });

            modelBuilder.Entity("TipoReporte", b =>
                {
                    b.Property<int>("TipoReporteID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TipoReporteID"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("TipoReporteID");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("TiposReporte");
                });

            modelBuilder.Entity("TipoServicio", b =>
                {
                    b.Property<int>("TipoServicioID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TipoServicioID"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("TipoServicioID");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("TiposServicio");
                });

            modelBuilder.Entity("TipoUsuario", b =>
                {
                    b.Property<int>("TipoUsuarioID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TipoUsuarioID"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("TipoUsuarioID");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("TiposUsuario");
                });

            modelBuilder.Entity("Usuario", b =>
                {
                    b.Property<int>("UsuarioID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UsuarioID"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Calle")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FirebaseUID")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("MotivoDesactivar")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("NumeroCasa")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<int>("PersonaID")
                        .HasColumnType("int");

                    b.Property<int>("TipoUsuarioID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UltimoAcceso")
                        .HasColumnType("datetime2");

                    b.HasKey("UsuarioID");

                    b.HasIndex("FirebaseUID")
                        .IsUnique();

                    b.HasIndex("PersonaID")
                        .IsUnique();

                    b.HasIndex("TipoUsuarioID");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("AlertaPanico", b =>
                {
                    b.HasOne("Usuario", "Usuario")
                        .WithMany("AlertasPanico")
                        .HasForeignKey("UsuarioID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Amenidad", b =>
                {
                    b.HasOne("TipoAmenidad", "TipoAmenidad")
                        .WithMany("Amenidades")
                        .HasForeignKey("TipoAmenidadID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TipoAmenidad");
                });

            modelBuilder.Entity("Aviso", b =>
                {
                    b.HasOne("CategoriaAviso", "Categoria")
                        .WithMany("Avisos")
                        .HasForeignKey("CategoriaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Usuario", "Usuario")
                        .WithMany("Avisos")
                        .HasForeignKey("UsuarioID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("CargoMantenimiento", b =>
                {
                    b.HasOne("PersonalMantenimiento", "PersonalMantenimiento")
                        .WithMany("CargosMantenimiento")
                        .HasForeignKey("PersonalMantenimientoID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Usuario", "Usuario")
                        .WithMany("CargosMantenimiento")
                        .HasForeignKey("UsuarioID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("PersonalMantenimiento");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("CargoServicio", b =>
                {
                    b.HasOne("SolicitudesServicio", "Solicitud")
                        .WithMany("CargosServicios")
                        .HasForeignKey("SolicitudID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Usuario", "Usuario")
                        .WithMany("CargosServicios")
                        .HasForeignKey("UsuarioID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Solicitud");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ComprobantePago", b =>
                {
                    b.HasOne("Pago", "Pago")
                        .WithOne("Comprobante")
                        .HasForeignKey("ComprobantePago", "PagoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pago");
                });

            modelBuilder.Entity("CuentaUsuario", b =>
                {
                    b.HasOne("Usuario", "Usuario")
                        .WithOne("CuentaUsuario")
                        .HasForeignKey("CuentaUsuario", "UsuarioID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("DetallePago", b =>
                {
                    b.HasOne("Pago", "Pago")
                        .WithMany("DetallesPago")
                        .HasForeignKey("PagoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pago");
                });

            modelBuilder.Entity("Invitado", b =>
                {
                    b.HasOne("Usuario", "Usuario")
                        .WithMany("Invitados")
                        .HasForeignKey("UsuarioID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("MarcadorMapa", b =>
                {
                    b.HasOne("Usuario", "Usuario")
                        .WithMany("MarcadoresMapa")
                        .HasForeignKey("UsuarioID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Pago", b =>
                {
                    b.HasOne("CargoMantenimiento", "CargoMantenimiento")
                        .WithMany("Pagos")
                        .HasForeignKey("CargoMantenimientoID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CargoServicio", "CargoServicio")
                        .WithMany("Pagos")
                        .HasForeignKey("CargoServicioID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Usuario", "Usuario")
                        .WithMany("Pagos")
                        .HasForeignKey("UsuarioID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CargoMantenimiento");

                    b.Navigation("CargoServicio");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("PersonalMantenimiento", b =>
                {
                    b.HasOne("Persona", "Persona")
                        .WithOne("PersonalMantenimiento")
                        .HasForeignKey("PersonalMantenimiento", "PersonaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("QRPersonal", b =>
                {
                    b.HasOne("Usuario", "Usuario")
                        .WithMany("QRPersonales")
                        .HasForeignKey("UsuarioID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Reporte", b =>
                {
                    b.HasOne("TipoReporte", "TipoReporte")
                        .WithMany("Reportes")
                        .HasForeignKey("TipoReporteID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Usuario", "Usuario")
                        .WithMany("Reportes")
                        .HasForeignKey("UsuarioID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("TipoReporte");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Reserva", b =>
                {
                    b.HasOne("Amenidad", "Amenidad")
                        .WithMany("Reservas")
                        .HasForeignKey("AmenidadID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Usuario", "Usuario")
                        .WithMany("Reservas")
                        .HasForeignKey("UsuarioID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Amenidad");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ServiciosCatalogo", b =>
                {
                    b.HasOne("TipoServicio", "TipoServicio")
                        .WithMany("ServiciosCatalogo")
                        .HasForeignKey("TipoServicioID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TipoServicio");
                });

            modelBuilder.Entity("SolicitudesServicio", b =>
                {
                    b.HasOne("ServiciosCatalogo", "ServicioAsignado")
                        .WithMany("SolicitudesServicio")
                        .HasForeignKey("PersonaAsignado");

                    b.HasOne("TipoServicio", "TipoServicio")
                        .WithMany("SolicitudesServicio")
                        .HasForeignKey("TipoServicioID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Usuario", "Usuario")
                        .WithMany("SolicitudesServicio")
                        .HasForeignKey("UsuarioID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ServicioAsignado");

                    b.Navigation("TipoServicio");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Usuario", b =>
                {
                    b.HasOne("Persona", "Persona")
                        .WithOne("Usuario")
                        .HasForeignKey("Usuario", "PersonaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TipoUsuario", "TipoUsuario")
                        .WithMany("Usuarios")
                        .HasForeignKey("TipoUsuarioID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Persona");

                    b.Navigation("TipoUsuario");
                });

            modelBuilder.Entity("Amenidad", b =>
                {
                    b.Navigation("Reservas");
                });

            modelBuilder.Entity("CargoMantenimiento", b =>
                {
                    b.Navigation("Pagos");
                });

            modelBuilder.Entity("CargoServicio", b =>
                {
                    b.Navigation("Pagos");
                });

            modelBuilder.Entity("CategoriaAviso", b =>
                {
                    b.Navigation("Avisos");
                });

            modelBuilder.Entity("Pago", b =>
                {
                    b.Navigation("Comprobante");

                    b.Navigation("DetallesPago");
                });

            modelBuilder.Entity("Persona", b =>
                {
                    b.Navigation("PersonalMantenimiento");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("PersonalMantenimiento", b =>
                {
                    b.Navigation("CargosMantenimiento");
                });

            modelBuilder.Entity("ServiciosCatalogo", b =>
                {
                    b.Navigation("SolicitudesServicio");
                });

            modelBuilder.Entity("SolicitudesServicio", b =>
                {
                    b.Navigation("CargosServicios");
                });

            modelBuilder.Entity("TipoAmenidad", b =>
                {
                    b.Navigation("Amenidades");
                });

            modelBuilder.Entity("TipoReporte", b =>
                {
                    b.Navigation("Reportes");
                });

            modelBuilder.Entity("TipoServicio", b =>
                {
                    b.Navigation("ServiciosCatalogo");

                    b.Navigation("SolicitudesServicio");
                });

            modelBuilder.Entity("TipoUsuario", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("Usuario", b =>
                {
                    b.Navigation("AlertasPanico");

                    b.Navigation("Avisos");

                    b.Navigation("CargosMantenimiento");

                    b.Navigation("CargosServicios");

                    b.Navigation("CuentaUsuario");

                    b.Navigation("Invitados");

                    b.Navigation("MarcadoresMapa");

                    b.Navigation("Pagos");

                    b.Navigation("QRPersonales");

                    b.Navigation("Reportes");

                    b.Navigation("Reservas");

                    b.Navigation("SolicitudesServicio");
                });
#pragma warning restore 612, 618
        }
    }
}
